server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy to auth service
    location /api/auth {
        proxy_pass http://backend-mongo:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /uploads {
        proxy_pass http://backend-mongo:5001;
    }

    # Proxy to slots service
    location /api/slots {
        proxy_pass http://backend-postgres:5002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/admin {
        proxy_pass http://backend-postgres:5002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
